version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: very_strong_password
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: ./backend
    container_name: my_app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/my_database
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: very_strong_password
  frontend:
    build: ./client-project-app
    container_name: my_frontend
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  mysql_data:
# networks:
#   default:
#     driver: bridge
#     name: app_network